# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 11:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_set',
            field=models.CharField(default=datetime.datetime(2016, 4, 27, 11, 4, 44, 844725, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
